stages:
  - test
  - deploy

Testing:
  image: python:3.6
  stage: test
  before_script:
    - wget -q -O - "https://dl-ssl.google.com/linux/linux_signing_key.pub" | apt-key add -
    - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
    - wget https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
    - apt-get update -q
    - apt-get install -y unzip
    - apt-get install -y google-chrome-stable
    - apt-get install -y xvfb
    - unzip chromedriver_linux64.zip chromedriver -d /usr/local/bin/
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py collectstatic --no-input
    - python manage.py runserver 8000 &
  when: on_success
  script:
    - coverage run --include='tugas/*' manage.py test
    - coverage report -m

Deployment:
  type: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=mobiltermurah --api-key=$HEROKU_APIKEY
  only:
    - master
