# Generated by Django 2.0.6 on 2020-05-09 05:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleTitle', models.CharField(max_length=60)),
                ('articleContent', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(max_length=30)),
                ('carYear', models.CharField(max_length=4)),
                ('carCity', models.CharField(max_length=50)),
                ('carPrice', models.CharField(max_length=15)),
                ('carDescription', models.CharField(max_length=1000)),
                ('carImage', models.ImageField(default='static/img/Car.png', upload_to='media/')),
                ('carRating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carReview', models.CharField(max_length=1000)),
                ('carRating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('carName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugas.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionDuration', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('carName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugas.Car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='carCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugas.Category'),
        ),
    ]
