# Generated by Django 2.0.13 on 2019-03-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Porto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judulProyek', models.CharField(max_length=100)),
                ('tanggalmulai', models.DateField()),
                ('tanggalselesai', models.DateField()),
                ('deskripsi', models.TextField()),
                ('tempat', models.CharField(max_length=100)),
                ('kategori', models.CharField(max_length=20)),
            ],
        ),
    ]
