# Generated by Django 2.0.13 on 2019-03-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='porto',
            old_name='judulProyek',
            new_name='judulproyek',
        ),
    ]
