# Generated by Django 2.0.6 on 2020-02-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0002_auto_20190302_0039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Porto',
        ),
    ]
