# Generated by Django 3.0.3 on 2020-05-09 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tugas', '0002_car_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='favorite',
            field=models.ManyToManyField(blank=True, default=False, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
