# Generated by Django 3.0.3 on 2020-05-10 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tugas', '0003_auto_20200509_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='favorite',
        ),
        migrations.AddField(
            model_name='car',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
