# Generated by Django 2.0.6 on 2020-03-05 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tugas', '0003_delete_porto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleContent', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(max_length=30)),
                ('carCategory', models.CharField(max_length=20)),
                ('carYear', models.CharField(max_length=4)),
                ('carCity', models.CharField(max_length=50)),
                ('carPrice', models.CharField(max_length=15)),
                ('carDescription', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugas.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugas.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugas.Car')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='carName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugas.Car'),
        ),
    ]
