# Generated by Django 3.0.2 on 2020-03-05 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0004_auto_20200305_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='articleContent',
        ),
    ]
