# Generated by Django 3.0.3 on 2020-05-11 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tugas', '0004_auto_20200511_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite_car', to=settings.AUTH_USER_MODEL),
        ),
    ]
