# Generated by Django 3.0.2 on 2020-03-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0005_remove_article_articlecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryName',
            field=models.CharField(default='black', max_length=20),
            preserve_default=False,
        ),
    ]
