# Generated by Django 3.0.2 on 2020-03-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0006_category_categoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='articleContent',
            field=models.CharField(default='This is a new car. Good quality', max_length=1000),
            preserve_default=False,
        ),
    ]
