# Generated by Django 3.0.2 on 2020-03-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0008_auto_20200305_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='carName',
        ),
        migrations.AddField(
            model_name='article',
            name='articleContent',
            field=models.CharField(default='test', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='articleTitle',
            field=models.CharField(default='test', max_length=60),
            preserve_default=False,
        ),
    ]
