# Generated by Django 3.0.2 on 2020-03-05 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0009_auto_20200305_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='carCategory',
        ),
        migrations.AlterField(
            model_name='car',
            name='carCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugas.Category'),
        ),
    ]
