# Generated by Django 2.0.6 on 2020-03-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0010_auto_20200305_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carImage',
            field=models.ImageField(default='static/img/Car.png', upload_to='media/'),
        ),
    ]
