# Generated by Django 2.0.6 on 2020-03-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0011_car_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='carRating',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
