# Generated by Django 3.0.2 on 2020-03-06 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0013_auto_20200306_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carRating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
