# Generated by Django 2.1.5 on 2020-05-08 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0014_car_carrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='articleRating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
