# Generated by Django 2.1.5 on 2020-05-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0016_articlereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlereview',
            name='articleTitle',
        ),
        migrations.AddField(
            model_name='article',
            name='totalRatings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ArticleReview',
        ),
    ]
