# Generated by Django 2.1.5 on 2020-05-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0017_auto_20200508_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='articleTitle',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
