# Generated by Django 2.1.5 on 2020-05-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0018_auto_20200515_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sumOfRatings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
